language:
    - c
    - cpp

sudo: required
dist: xenial

addons:
  apt:
    packages:
      - valgrind

env:
  global:
    - PROTOBUF_VERSION=3.6.1
    - PKG_CONFIG_PATH=$HOME/protobuf-$PROTOBUF_VERSION-bin/lib/pkgconfig

install:
    - wget https://github.com/google/protobuf/archive/v$PROTOBUF_VERSION.tar.gz
    - tar xf v$PROTOBUF_VERSION.tar.gz
    - ( cd protobuf-$PROTOBUF_VERSION && ./autogen.sh && ./configure --prefix=$HOME/protobuf-$PROTOBUF_VERSION-bin && make -j2 && make install )

script:
    - ./autogen.sh
    - ./configure && make -j2 distcheck VERBOSE=1 && make clean
    - ./configure --enable-valgrind-tests CFLAGS="-fsanitize=undefined -fno-sanitize-recover=undefined" && make -j2 distcheck DISTCHECK_CONFIGURE_FLAGS="--enable-valgrind-tests CFLAGS=\"-fsanitize=undefined -fno-sanitize-recover=undefined\"" VERBOSE=1 && make clean
